### ISSUE TITLE
I am thoroughly confused

### ISSUE THREAD

**Issue by FreeBSD-fan** [EndPointCorp/end-point-blog#2035]
When I encrypted my LUKS root partition, I entered a passphrase, and when I boot the machine, linux makes me enter that passphrase.  Do I put that passphrase in lkluks.cfg:
YUBIKEY_CHALLENGE="[your new passphrase here]" ?

My yubikey doesn't arrive until Monday, I'm just trying to figure it out before it gets here.  I ordered a YubiKey 5 Nano.
And I noticed the debian repository has the 0.5 version one (and 0.6 version is needed).

`apt show yubikey-luks
Package: yubikey-luks
Version: 0.5.1+29.g5df2b95-6build1
`

**Comment by obnoxiousorc** [comment]
Hi! To your first question, no - the passphrase you put there is the one you created in step 3. Your old passphrase should correspond with slot 0 in your LUKS config, and the YubiKey should be added to one you choose (but definitely not 0); that way the old passphrase is still a valid authentication method completely unrelated to your YubiKey.

As for the version, I'm not sure - if it's a newer YubiKey you're using, it's possible you'll have to get the newer version of `yubikey-luks` from somewhere else. I think it was up to date when I wrote the blog post.

**Comment by sethjensen1** [comment]
Hi,

the issues in this repo are reserved for blog posts. To leave a comment on a post please go to the associated issue and leave a comment on the issue, instead of creating a new issue. I've copied these comments over to the original post in case you want to continue the conversation: https://github.com/EndPointCorp/end-point-blog/issues/1838#issuecomment-2028555175

Thanks for reading!
