### ISSUE TITLE
enroll times out quicker than I can touch the yubikey

### ISSUE THREAD

**Issue by FreeBSD-fan** [EndPointCorp/end-point-blog#2038]
When I try to enroll into slot 1, enroll times out quicker than I can touch the yubikey.  I even tried touching the yubikey before hitting return.

`sudo yubikey-luks-enroll -d /dev/sda3 -s 1
setting disk to /dev/sda3.
setting slot to 1.
This script will utilize slot 1 on drive /dev/sda3.  If this is not what you intended, exit now!
Adding yubikey to initrd
Please enter the yubikey challenge password. This is the password that will only work while your yubikey is installed in your computer:
Please enter the yubikey challenge password again:
Yubikey not available or timed out waiting for button press`

**Comment by sethjensen1** [comment]
Hi @FreeBSD-fan,

The issues in this repo are reserved for blog posts. To leave a comment on a post please go to the associated issue (https://github.com/EndPointCorp/end-point-blog/issues/1838) and leave a comment on the issue, instead of creating a new issue. I've copied your comment over to the original post so you can continue the conversation there.

Thanks for reading!
